---

stages:
  - info
  - lint
  - molecule

before_script:
  - test -f requirements.tmpl && envsubst < requirements.tmpl > requirements.yaml
  - test -f molecule/default/requirements.tmpl && envsubst < molecule/default/requirements.tmpl > molecule/default/requirements.yaml

variables:
  VENV: /home/gitlab-runner/venv/ansible-current
  #PY_COLORS: '1'
  #ANSIBLE_FORCE_COLOR: '1'
  MOLECULE_PLAYBOOK: converge.yml

info:
  stage: info
  script:
    - hostname -f

yamllint:
  stage: lint
  script:
    - source $VENV/bin/activate
    - yamllint .

ansible-lint:
  stage: lint
  script:
    - source $VENV/bin/activate
    - ansible-lint

centos7:
  stage: molecule
  script:
    - source $VENV/bin/activate
    - molecule test
  variables:
    MOLECULE_DISTRO: centos7
centos8:
  stage: molecule
  script:
    - source $VENV/bin/activate
    - molecule test
  variables:
    MOLECULE_DISTRO: centos8
debian10:
  stage: molecule
  script:
    - source $VENV/bin/activate
    - molecule test
  variables:
    MOLECULE_DISTRO: debian10
debian11:
  stage: molecule
  script:
    - source $VENV/bin/activate
    - molecule test
  variables:
    MOLECULE_DISTRO: debian11
ubuntu1804:
  stage: molecule
  script:
    - source $VENV/bin/activate
    - molecule test
  variables:
    MOLECULE_DISTRO: ubuntu1804
ubuntu2004:
  stage: molecule
  script:
    - source $VENV/bin/activate
    - molecule test
  variables:
    MOLECULE_DISTRO: ubuntu2004
