---

- name: Prepare
  hosts: all
  become: yes
  tasks:

    - block:

        - name: Update APT cache
          apt:
            update_cache: yes
            cache_valid_time: 1
    
      when: ansible_os_family == 'Debian'
    
    - block:

        - name: Update DNF cache
          command: yum makecache
          args:
            warn: false
    
      when: ansible_os_family == 'RedHat'
